### PR TITLE
Fixes #12561 - Changes for Rails 4

### PR DESCRIPTION
**Pull request by xprazak2**
- attr_accessible for models
- changed the way migrations are included
- not changing PUT to PATCH yet for backward compatibility

### CODE REVIEW

**Comment by xprazak2** [comment]
@unorthodoxgeek, could you pls do a quick scan if this seems ok to you?

**Comment by unorthodoxgeek** [comment]
on pto today, will do tomorrow.

**Comment by unorthodoxgeek** [comment]
code changes look ok to me.
did you test the functionality?

**Comment by xprazak2** [comment]
I found out I missed :organization_id in one of my models, good thing I double-checked. Thx @unorthodoxgeek!

**Pull request merged**
